Django Project - News Agregator/myproject/blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.post_list_view, name='blog'),
    url(r'post/(?P<post_id>\d+)/$', views.post_detail_view, name="post_detail_view"),
    url(r'category/(?P<category_name>\w+)/$', views.posts_in_category, name="post_in_category"),

]

Django Project - News Agregator/myproject/myapp/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views 

app_name = 'myapp'
urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^contact/$', views.contact, name="contact"),
    url(r'^about/$', views.about, name="about"),
    url(r'^about-me/$', views.about, name="about"),
]

Django Project - News Agregator/myproject/myproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('myapp.urls')),
    url(r'^science-news/', include('news.urls')),
    url(r'^blog/', include('blog.urls')),

]

Django Project - News Agregator/myproject/news/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views 

app_name= 'news'
urlpatterns = [
    url(r'^(?P<source>[a-z-]+)/$', views.index, name="index"),
    url(r'^$', views.index, name="home")
]

Django Project - News Agregator/myproject/blog/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
	name=models.CharField(max_length=30)
	description = models.TextField(null=True, blank=True)

	class Meta:
		verbose_name_plural = "Categories"

	def __str__(self):
		return self.name

class Post(models.Model):
	title = models.CharField(max_length=140)
	body = models.TextField()
	date_publish = models.DateTimeField()
	date_create = models.DateTimeField(auto_now_add=True)
	date_update = models.DateTimeField(auto_now=True)
	public = models.BooleanField(default=True)
	category = models.ForeignKey(Category, null=True)

	def __str__(self):
		return self.title

Django Project - News Agregator/myproject/myapp/models.py
from django.db import models

# Create your models here.

Django Project - News Agregator/myproject/news/models.py
from django.db import models

# Create your models here.

Django Project - News Agregator/myproject/blog/views.py
from django.shortcuts import render

from .models import Post
# Create your views here.
def post_list_view(request):
	context = {
		'object_list': Post.objects.filter(public=True).order_by("-date_publish")
	}

	return render(request, 'blog/post_list.html', context)

def post_detail_view(request, post_id):
	context = { 'object': Post.objects.get(id=post_id)}
	return render(request, 'blog/post_detail.html', context)


def posts_in_category(request, category_name):
	context = { 'object_list': Post.objects.filter(category__name=category_name) }
	return render(request, 'blog/post_list.html', context)

Django Project - News Agregator/myproject/myapp/views.py
import random
from django.shortcuts import render

# Create your views here.
def home(request):
    num = random.randint(1, 100)
    some_list = [
       random.randint(1, 100000),
       random.randint(1, 100000),
       random.randint(1, 100000),
    ]
    context = {
      'bool_item': True,
      'num': num,
      'list': some_list
    }
    return render(request, 'myapp/home.html', context)


def contact(request):
    return render(request, 'myapp/contact.html')

def about(request):
    tvseries = [
        {'title': 'Game of Thrones', 'seasons': 7, 'genre': 'fantasy', 'year': 2011, 'ongoing': True},
        {'title': 'Breaking Bad', 'seasons': 5, 'genre': 'drama', 'year': 2008, 'ongoing': False},
        {'title': 'Sons of Anarchy', 'seasons': 7, 'genre': 'crime drama', 'year': 2008, 'ongoing': False},
        {'title': 'The Big Bang Theory', 'seasons': 10, 'genre': 'comedy', 'year': 2007, 'ongoing': True},
        {'title': 'Silicon Valley', 'seasons': 4, 'genre': 'comedy', 'year': 2014, 'ongoing': True},
        {'title': 'The Walking Dead', 'seasons': 7, 'genre': 'horror', 'year': 2010, 'ongoing': True},
    ]
    context = {
      'lucky_num': random.randint(1, 10),
      'unlucky_num': random.randint(1, 10),
      'tvseries': tvseries
    }
    return render(request, 'myapp/about.html', context)

Django Project - News Agregator/myproject/news/views.py
from django.shortcuts import render
import json
import urllib.request

# Create your views here.
def index(request, source = "new-scientist"):


  url = 'https://newsapi.org/v1/articles?source={}'.format(source)
  url += '&sortBy=top&apiKey=d754b116d9fe46c2ad4d4e33b23e0f52'

  page = urllib.request.urlopen(url)
  string = page.read().decode()
  data = json.loads(string)
  sources = ['ars-technica', 'bbc-news', 'hacker-news', 'national-geographic', 'new-scientist', 'techradar']
  current_site = source
  context = {'newsapi': data, 'sources_key' : sources, 'selected_site': current_site}
  return render(request, 'news/index.html', context)

Django Project - News Agregator/myproject/blog/templates/blog/post_detail.html
{% extends 'myapp/base.html' %}
{% block nav-item-blog%} active {% endblock %}

{% block page_title%}Blog{% endblock %}

{% block content%}

  
    <div class="container">
    <div class="col-4">
    <h1 class="display-4">Blog</h1>
    <hr class="my-4">
        <h2> {{ object.title }} </h2>
        <p> {{ object.body}} </p>
        <p> {{ object.date_publish }} </p>
    
    </div>
    </div>



    
  

{% endblock %}

Django Project - News Agregator/myproject/blog/templates/blog/post_list.html
{% extends 'myapp/base.html' %}
{% block nav-item-blog%} active {% endblock %}
{% block page_title%}Blog{% endblock %}
{% block content%}

<div class="container">
<div class="row">
   <div class="col-12">
      <h1>Blog</h1>
      <div class="list-group">
         {% for obj in object_list%}
         <div class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
               <h5 class="mb-1">{{ obj.title|title }}</h5>
               <small> {{ obj.date_publish|timesince}} ago</small>
            </div>
            <p class="mb-1">{{ obj.body|truncatewords:5}}</p>
            <br>
            <a href="{% url 'blog:post_detail_view' obj.id %}" class="btn btn-dark btn-sm">Read More</a>
            </br>
            <br>
            <small class="blog-post-meta"> <a href="#">Kaczy</a></small>
            <small>Updated: {{ obj.date_update}}</small>
            </br>
         </div>
         {% empty %}
         <h2 class="blog-post-title">Sorry no posts here</h2>
         {% endfor %}
      
      </div>
   </div>
</div>
</div>
{% endblock %}

Django Project - News Agregator/myproject/myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}
{% block nav-item-about%} active {% endblock %}

{% block page_title%}About{% endblock %}

{% block content%}

    
    <div class="container">
      <img src="profile.jpg" class="rounded-circle float-right" alt="Foto" width="120px">
      <h1 class="display-4">About</h1>
      <p class="lead">I'm a <span class="text-primary">#bioinformatics</span> student obsessed with #molecular biology, #web technologies and #beer.</p>
      <hr class="my-4">
      <p>I'm interested in molecular basis of genetic diseases as well as my games addiction. Also I like trains. And below there is list of my TV series</p>
 

    <!-- begin::Table -->
    <div class="table-striped">
    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Genre</th>
          <th>Year</th>
          <th>Seasons</th>
          <th>Playing</th>
        </tr>
      </thead>
      <tbody>
      {% for row in tvseries %}
        <tr>
          <td>{{ row.title }}</td>
          <td>{{ row.genre|capfirst }}</td>
          <td>{{ row.year }}</td>
          <td>{{ row.seasons }}</td>
          <td>{{ row.ongoing|yesno:"yes,no" }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
         </div>
    <!-- end::Table -->
{% endblock %}

Django Project - News Agregator/myproject/myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'myapp/plugins/bootstrap/css/bootstrap.min.css'  %}" >
  <title>{% block page_title%}Home{% endblock %}</title>
  <style>
    .jumbotron {
      padding:30px;
    }
    footer {
      padding-top: 20px;
      margin-top: 20px;
      color: #777;
      border-top: 1px solid #e5e5e5;
    }
    .nav-link {
      color: #212529;
    }
    .nav-link:hover {
      color:darkgrey;
    }    
    .nav-pills .nav-link.active {
      background-color:grey;
    }
  </style>
</head>

<body>
  <!-- begin::Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><img src="https://blog.ciavash.name/assets/img/icon/fa-home.svg" height="30px"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item {% block nav-item-home%}{% endblock %}">
            <a class="nav-link" href="{% url 'myapp:home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item {% block nav-item-news%}{% endblock %}">
            <a class="nav-link" href="{% url 'news:home' %}">News</a>
          </li>
          <li class="nav-item {% block nav-item-about%}{% endblock %}">
            <a class="nav-link" href="{% url 'myapp:about' %}">About Me</a>
          </li>
          <li class="{% block nav-item-blog%}{% endblock %}">
            <a class="nav-link" href="{% url 'blog:blog' %}">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Research</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Tools</a>
          </li>
          <li class="nav-item {% block nav-item-contact%}{% endblock %}">
            <a class="nav-link" href="{% url 'myapp:contact' %}">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- end::Navigation -->

  </body>

  {% block content %}

  {% endblock %}


  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </html>

Django Project - News Agregator/myproject/myapp/templates/myapp/contact.html
{% extends 'myapp/base.html' %}
{% block nav-item-contact%} active {% endblock %}

{% block page_title%}Contact{% endblock %}

{% block content%}

  
    <div class="container">
    <h1 class="display-4">Contact</h1>
      <p class="lead"><span class="text-primary">Telefon:</span> 500848364</p>
      <hr class="my-4">
     

    </div>

  

{% endblock %}

Django Project - News Agregator/myproject/myapp/templates/myapp/home.html
{% extends 'myapp/base.html' %}
{% block nav-item-home %} active {% endblock %}


{% block content %}

  <!-- begin::Jumbotron -->
  <div class="jumbotron">
    <div class="container">
      <img src="profile.jpg" class="rounded-circle float-right" alt="Foto" width="120px">
      <h1 class="display-3">Home</h1>
      <p class="lead">I'm a <span class="text-primary">#bioinformatics</span> student obsessed with #molecular biology, #web technologies and #beer.</p>
      <hr class="my-4">
      <p>I'm interested in molecular basis of genetic diseases as well as my coffee addiction.</p>
      <p class="lead">
        <a class="btn btn-primary btn-sm" href = "/about/">Read more</a>
      </p>
    </div>
  </div>
  <!-- end::Jubotron -->

  <!-- begin:Container -->
  <div class="container">
    <div class="row">
      <!-- begin::Column 1 -->
      <div class="col-3">
        <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist">
          <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-expanded="true">Short Bio</a>
          <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-expanded="true">My Projects</a>
          <a class="nav-link" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-expanded="true">Whatever 1</a>
          <a class="nav-link" id="v-pills-settings-tab" data-toggle="pill" href="#v-pills-settings" role="tab" aria-controls="v-pills-settings" aria-expanded="true">Whatever 2</a>
        </div>
      </div>
      <!-- end::Column 1 -->
      <!-- begin:Column 2 -->
      <div class="col-5">
        <!-- begin:: Tab Content -->
        <div class="tab-content" id="v-pills-tabContent">
          <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, <mark>sed do eiusmod tempor</mark> incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris <code>nisi ut aliquip</code> ex ea commodo consequat.</p>
            <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint <strong>occaecat cupidatat non</strong> proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            <blockquote class="blockquote">
              <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
              <footer class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></footer>
            </blockquote>
          </div>
          <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">...</div>
          <div class="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">...</div>
          <div class="tab-pane fade" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">...</div>
        </div>
        <!-- end::Tab Content -->
      </div>
      <!-- end::Column 2 -->
      <!-- begin::Column 3 -->
      <div class="col-4">
        <h4>My latest works <span class="badge badge-secondary badge-info">New</span></h4>
        <!-- begin::Carousel -->
        <div id="carouselExample" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExample" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExample" data-slide-to="1"></li>
            <li data-target="#carouselExample" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img class="d-block w-100" src="http://via.placeholder.com/300x250" alt="First slide">
              <div class="carousel-caption d-none d-md-block">
                <h4>Website 1</h4>
                <p>sample text</p>
              </div>
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="http://via.placeholder.com/300x250" alt="Second slide">
              <div class="carousel-caption d-none d-md-block">
                <h3>Graphic 1</h3>
                <p>sample text</p>
              </div>
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="http://via.placeholder.com/300x250" alt="Third slide">
              <div class="carousel-caption d-none d-md-block">
                <h3>Graphic 2</h3>
                <p>sample text</p>
              </div>
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExample" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExample" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
          </a>
        </div>
        <!-- end::Carousel -->
      </div>
      <!-- end::Column 3 -->
    </div>
    <!-- begin:Footer -->
    <footer class="footer">
      <p>© Company 2017</p>
    </footer>
    <!-- end::Footer -->
  </div>
  <!-- end::Container -->
  
{% endblock %}

Django Project - News Agregator/myproject/myapp/templates/myapp/includes/widget.html
<div style="width: 100px;height: 100px; background-color: hotpink;">
      widget
</div>

Django Project - News Agregator/myproject/myapp/templates/myapp/news.html
{% extends 'myapp/base.html' %}
{% block nav-item-news%} active {% endblock %}
{% block page_title%}News{% endblock %}
{% block content%}
<div class="container">
<h1 class="display-4">News</h1>
	<a href="/news/ars-technica">Ars Technica</a> |
	<a href="/news/bbc-news">BBC</a> |
	<a href="/news/hacker-news">Hacker News</a> |
	<a href="/news/national-geographic">National Geographic</a> |
	<a href="/news/new-scientist">New Scientist</a> |
	<a href="/news/techradar"> TechRadar</a>
{% if newsapi.status == 'ok' %}
<div class="card-columns">
   {% for article in newsapi.articles %}
   <div class="card">
      <img class="card-img-top" src="{{ article.urlToImage }}" alt="{{ article.title|slugify }}">
      <div class="card-body">
         <h4 class="card-title"><a target="_blank" href="{{article.url}}">{{ article.title }}</a></h4>
         <p class="card-text">{{ article.description }}</p>
         <p class="card-text"><small class="text-muted">{{ article.publishedAt }}</small></p>
      </div>
      </div>
      {% endfor %}
   </div>
   {% endif %}
   <hr class="my-4">
</div>
{% endblock %}

Django Project - News Agregator/myproject/news/templates/news/index.html
{% extends 'myapp/base.html' %}
{% block nav-item-news%} active {% endblock %}
{% block page_title%}News{% endblock %}
{% block content%}
<div class="container">
<h1 class="display-4">News</h1>

<div class="btn-group">
	{% for source in sources_key %}
   {% if source == selected_site %}
      
      <button type="button" class="btn btn-dark btn-sm" disabled>{% filter upper %}{{ source }}{% endfilter %}</button>
       

   {% else %}
       <a href="{% url 'news:index' source  %}" class="btn btn-dark btn-sm">{% filter upper %}{{source}}{% endfilter %}</a>
   {% endif %}

   {% endfor %}
   </div>
<hr class="my-4">



{% if newsapi.status == 'ok' %}
<div class="card-columns">
   {% for article in newsapi.articles %}
   <div class="card">
      <img class="card-img-top" src="{{ article.urlToImage }}" alt="{{ article.title|slugify }}">
      <div class="card-body">
         <h4 class="card-title"><a target="_blank" href="{{article.url}}">{{ article.title }}</a></h4>
         <p class="card-text">{{ article.description }}</p>
         <p class="card-text"><small class="text-muted">{{ article.publishedAt }}</small></p>
      </div>
      </div>
      {% endfor %}
   </div>
   {% else %}
   <div class="alert alert-warning" role="alert">
         Sorry, no news were found. Try again later.
   </div>
   {% endif %}
   
</div>
{% endblock %}